#!/usr/bin/env python3

import sys

def calcul(array):
    try:
        for i in range(0, 1001):
            res = 1
            for x in range(0, len(array), 2):
                a = 0
                b = 0
                if array[x] != array[x + 1]:
                    for j in range(0, len(array[x])):
                        a += array[x][j] * ((i / 1000) ** j)
                    for j in range(0, len(array[x + 1])):
                        b += array[x + 1][j] * ((i / 1000) ** j)
                    res *= (a / b)
            print("%.3f -> %.5f" % (i / 1000, res))
    except DivisionZero:
        print("division by zero")
        exit(84)
    
def help():
    print("USAGE\n"
    "    ./107transfer [num den]*\n"
    "\n"
    "DESCRIPTION\n"
    "    num    polynomial numerator defined by its coeficients\n"
    "    den    polynomial denominator defined by its coeficients")
    exit(0)

def pass_in_int(array):
    try:
        for y in range(len(array)):
            for i in range(0, len(array[y])):
                array[y][i] = int(array[y][i])
        return (array)
    except ValueError:
        exit(84)

def check_and_get_arg(array) :
    for i in range(0, len(sys.argv) - 1) :
        array.append(sys.argv[i + 1].split("*"))
    array = pass_in_int(array)
    return (array)

if (len(sys.argv) == 2 and sys.argv[1] == "-h") :
    help()
if (len(sys.argv) % 2 == 0 or len(sys.argv) <= 2) :
    exit(84)
array = []
array = check_and_get_arg(array)
calcul(array)
